# This is testing the python versions *other than* the
#   one in the QUIP Docker, which is 3.7.10 at the time
#   of writing this. Coverage is disabled.

name: Build docs

# on all push actions AND can be triggered manually as well
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
      max-parallel: 5
    env:
      coverage-on-version: "3.9"
      use-mpi: True
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python-version }} via conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Check python version
        run: |
          which python3
          python3 --version

      - name: Install dependencies from pip
        run: python3 -m pip install wheel setuptools numpy scipy click matplotlib pyyaml spglib phonopy phono3py rdkit flake8 pytest pytest-cov nbsphinx ipython requests

      - name: Install latest ASE from gitlab
        run: |
          python3 -m pip install git+https://gitlab.com/ase/ase.git
          echo -n "ASE VERSION "
          python3 -c "import ase; print(ase.__file__, ase.__version__)"

      - name: Install Quippy from PyPI
        run: python3 -m pip install quippy-ase

      - name: Install wfl (expyre and universalSOAP are dependencies)
        run: python3 -m pip install .

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Build documentation
        run: |
          python3 -m pip install sphinx sphinx-book-theme docutils==0.16 sphinx-click myst-parser
          python3 -m pip install --upgrade jinja2
          cd docs
          make html
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
